---

- hosts: all
  vars:
    - username: "ajones"
  remote_user: root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes

  tasks:

    - name: create user account
      user:
        name: "{{ username }}"

    - name: Set public key from github
      authorized_key:
        user: "{{ username }}"
        state: present
        key: https://github.com/AdmaJonse.keys
    
    - name: install packages
      yum:
        name:
          - nfs-utils
          - python3
          - python3-pip

    - name: install python libraries
      pip:
        name:
          - pymongo
          - cherrypy
          - beautifulsoup4
          - bitstring